#!/usr/bin/env bash
# Install the redline-review skill into the user's global Claude skills directory
# so it's reachable from any project, not just this repo.
#
# This is a copy, not a symlink: the repo lives in paths that move (worktrees,
# renamed projects), and a stale symlink that vanishes is worse than a copy
# that needs an explicit refresh after pulling skill changes.
#
# We also generate a self-contained launcher next to the installed skill,
# with absolute paths to `bun` and `src/cli.ts` baked in. SKILL.md points
# at the launcher. This removes every $PATH dependency from the invocation
# chain — both `redline` itself AND the `#!/usr/bin/env bun` shebang it would
# otherwise resolve through PATH at runtime. (Real-usage failure: an outside
# session hit `env: bun: No such file or directory` because ~/.bun/bin isn't
# on $PATH in non-interactive Claude Bash subprocesses.)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$REPO_ROOT/skills/redline-review"
DEST="${CLAUDE_HOME:-$HOME/.claude}/skills/redline-review"
PLACEHOLDER="__REDLINE_BIN__"

if [ ! -d "$SRC" ]; then
  echo "error: skill source not found at $SRC" >&2
  exit 1
fi

CLI_ABS="$REPO_ROOT/src/cli.ts"
if [ ! -f "$CLI_ABS" ]; then
  echo "error: redline cli not found at $CLI_ABS" >&2
  exit 1
fi

# Resolve bun. Prefer $PATH; fall back to ~/.bun/bin/bun.
if command -v bun >/dev/null 2>&1; then
  BUN_ABS="$(command -v bun)"
elif [ -x "$HOME/.bun/bin/bun" ]; then
  BUN_ABS="$HOME/.bun/bin/bun"
else
  echo "error: bun not found in PATH or at ~/.bun/bin/bun (install: https://bun.sh)" >&2
  exit 1
fi

mkdir -p "$(dirname "$DEST")"
rm -rf "$DEST"
cp -R "$SRC" "$DEST"

# Generate a self-contained launcher with absolute paths to bun and cli.ts.
LAUNCHER="$DEST/redline"
cat > "$LAUNCHER" <<EOF
#!/bin/bash
# Auto-generated by scripts/install-skill.sh — re-run that script to refresh.
exec "$BUN_ABS" run "$CLI_ABS" "\$@"
EOF
chmod +x "$LAUNCHER"

# Substitute the launcher path into the installed SKILL.md.
SKILL_FILE="$DEST/SKILL.md"
if ! grep -q "$PLACEHOLDER" "$SKILL_FILE"; then
  echo "error: placeholder '$PLACEHOLDER' not found in $SKILL_FILE — source skill is out of sync" >&2
  exit 1
fi
if [[ "$OSTYPE" == "darwin"* ]]; then
  sed -i '' "s|$PLACEHOLDER|$LAUNCHER|g" "$SKILL_FILE"
else
  sed -i "s|$PLACEHOLDER|$LAUNCHER|g" "$SKILL_FILE"
fi

echo "Installed redline-review → $DEST"
echo "  launcher: $LAUNCHER"
echo "  bun:      $BUN_ABS"
echo "  cli:      $CLI_ABS"
echo
echo "Your AI coding agents (Claude Code, etc.) can now use the redline-review skill."
echo "Try it: ask your agent to redline a markdown file you'd like feedback on."
echo
echo "Re-run this script after pulling skill changes."
