#!/usr/bin/env bash
# Install the redline-review skill into a user's global agent skills directory
# so it's reachable from any project, not just this repo.
#
# This is a copy, not a symlink: the repo lives in paths that move (worktrees,
# renamed projects), and a stale symlink that vanishes is worse than a copy
# that needs an explicit refresh after pulling skill changes.
#
# We also generate a self-contained launcher next to the installed skill.
# When invoked through the packaged `redline` binary, the launcher points back
# to that durable binary. When invoked from a checkout, it bakes in absolute
# paths to `bun` and `src/cli.ts`. Either way, the skill does not depend on
# `redline` being on PATH in non-interactive agent subprocesses.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$REPO_ROOT/skills/redline-review"
PLACEHOLDER="__REDLINE_BIN__"
TARGET="both"

usage() {
  cat >&2 <<'EOF'
Usage: redline install-skill [--agent claude|codex|both]
       scripts/install-skill.sh [--agent claude|codex|both]

Installs the bundled redline-review skill into the selected agent environment:
  claude  -> $CLAUDE_HOME/skills/redline-review or ~/.claude/skills/redline-review
  codex   -> $CODEX_HOME/skills/redline-review or ~/.codex/skills/redline-review
  both    -> both locations (default)
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --agent)
      TARGET="${2:-}"
      shift 2
      ;;
    --agent=*)
      TARGET="${1#--agent=}"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

case "$TARGET" in
  claude|codex|both) ;;
  *)
    echo "error: --agent must be claude, codex, or both" >&2
    usage
    exit 1
    ;;
esac

if [ ! -d "$SRC" ]; then
  echo "error: skill source not found at $SRC" >&2
  exit 1
fi

CLI_ABS="$REPO_ROOT/src/cli.ts"
if [ ! -f "$CLI_ABS" ]; then
  echo "error: redline cli not found at $CLI_ABS" >&2
  exit 1
fi

LAUNCH_CMD=""
if [ -n "${REDLINE_BIN_ABS:-}" ] && [ -f "$REDLINE_BIN_ABS" ]; then
  LAUNCH_CMD="exec \"$REDLINE_BIN_ABS\" \"\$@\""
  BUN_ABS=""
else
  # Resolve bun. Prefer $PATH; fall back to ~/.bun/bin/bun.
  if command -v bun >/dev/null 2>&1; then
    BUN_ABS="$(command -v bun)"
  elif [ -x "$HOME/.bun/bin/bun" ]; then
    BUN_ABS="$HOME/.bun/bin/bun"
  else
    echo "error: bun not found in PATH or at ~/.bun/bin/bun (install: https://bun.sh)" >&2
    exit 1
  fi
  LAUNCH_CMD="exec \"$BUN_ABS\" run \"$CLI_ABS\" \"\$@\""
fi

install_one() {
  local label="$1"
  local dest="$2"

  mkdir -p "$(dirname "$dest")"
  rm -rf "$dest"
  cp -R "$SRC" "$dest"

  # Generate a self-contained launcher.
  local launcher="$dest/redline"
  cat > "$launcher" <<EOF
#!/bin/bash
# Auto-generated by scripts/install-skill.sh — re-run that script to refresh.
$LAUNCH_CMD
EOF
  chmod +x "$launcher"

  # Substitute the launcher path into the installed SKILL.md.
  local skill_file="$dest/SKILL.md"
  if ! grep -q "$PLACEHOLDER" "$skill_file"; then
    echo "error: placeholder '$PLACEHOLDER' not found in $skill_file — source skill is out of sync" >&2
    exit 1
  fi
  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "s|$PLACEHOLDER|$launcher|g" "$skill_file"
  else
    sed -i "s|$PLACEHOLDER|$launcher|g" "$skill_file"
  fi

  echo "Installed redline-review for $label → $dest"
  echo "  launcher: $launcher"
}

if [ "$TARGET" = "claude" ] || [ "$TARGET" = "both" ]; then
  install_one "Claude Code" "${CLAUDE_HOME:-$HOME/.claude}/skills/redline-review"
fi
if [ "$TARGET" = "codex" ] || [ "$TARGET" = "both" ]; then
  install_one "Codex" "${CODEX_HOME:-$HOME/.codex}/skills/redline-review"
fi

if [ -n "${BUN_ABS:-}" ]; then
  echo "  bun:      $BUN_ABS"
  echo "  cli:      $CLI_ABS"
else
  echo "  redline:  $REDLINE_BIN_ABS"
fi
echo
echo "Your AI coding agents can now use the redline-review skill."
echo "Try it: ask your agent to redline a markdown file you'd like feedback on."
echo
echo "Re-run this command after upgrading Redline if the skill instructions change."
